/* -------------------------------------------------------------------------- */
/*                                Code-Vibes                                  */
/* -------------------------------------------------------------------------- */
export let codeVibesArray:string[] = [
    "../assets/image/theme-img/code-vibes/memory-cards/cv-1.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-1.png", 
    "../assets/image/theme-img/code-vibes/memory-cards/cv-2.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-2.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-3.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-3.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-4.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-4.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-5.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-5.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-6.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-6.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-7.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-7.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-8.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-8.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-9.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-9.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-10.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-10.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-11.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-11.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-12.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-12.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-13.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-13.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-14.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-14.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-15.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-15.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-16.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-16.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-17.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-17.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-18.png",
    "../assets/image/theme-img/code-vibes/memory-cards/cv-18.png",

]

/* -------------------------------------------------------------------------- */
/*                                Da-Project                                  */
/* -------------------------------------------------------------------------- */
export let daProjectArray:string[] = [
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-1.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-1.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-2.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-2.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-3.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-3.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-4.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-4.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-5.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-5.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-6.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-6.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-7.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-7.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-8.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-8.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-9.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-9.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-10.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-10.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-11.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-11.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-12.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-12.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-13.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-13.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-14.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-14.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-15.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-15.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-16.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-16.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-17.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-17.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-18.png",
    "../assets/image/theme-img/da-projects/memory-cards/da-memory-18.png",
]

/* -------------------------------------------------------------------------- */
/*                                Game                                        */
/* -------------------------------------------------------------------------- */
export let gameArray:string[] = [
    "../assets/image/theme-img/game/memory-cards/gaming-1.png",
    "../assets/image/theme-img/game/memory-cards/gaming-1.png",
    "../assets/image/theme-img/game/memory-cards/gaming-2.png",
    "../assets/image/theme-img/game/memory-cards/gaming-2.png",
    "../assets/image/theme-img/game/memory-cards/gaming-3.png",
    "../assets/image/theme-img/game/memory-cards/gaming-3.png",
    "../assets/image/theme-img/game/memory-cards/gaming-4.png",
    "../assets/image/theme-img/game/memory-cards/gaming-4.png",
    "../assets/image/theme-img/game/memory-cards/gaming-5.png",
    "../assets/image/theme-img/game/memory-cards/gaming-5.png",
    "../assets/image/theme-img/game/memory-cards/gaming-6.png",
    "../assets/image/theme-img/game/memory-cards/gaming-6.png",
    "../assets/image/theme-img/game/memory-cards/gaming-7.png",
    "../assets/image/theme-img/game/memory-cards/gaming-7.png",
    "../assets/image/theme-img/game/memory-cards/gaming-8.png",
    "../assets/image/theme-img/game/memory-cards/gaming-8.png",
    "../assets/image/theme-img/game/memory-cards/gaming-9.png",
    "../assets/image/theme-img/game/memory-cards/gaming-9.png",
    "../assets/image/theme-img/game/memory-cards/gaming-10.png",
    "../assets/image/theme-img/game/memory-cards/gaming-10.png",
    "../assets/image/theme-img/game/memory-cards/gaming-11.png",
    "../assets/image/theme-img/game/memory-cards/gaming-11.png",
    "../assets/image/theme-img/game/memory-cards/gaming-12.png",
    "../assets/image/theme-img/game/memory-cards/gaming-12.png",
    "../assets/image/theme-img/game/memory-cards/gaming-13.png",
    "../assets/image/theme-img/game/memory-cards/gaming-13.png",
    "../assets/image/theme-img/game/memory-cards/gaming-14.png",
    "../assets/image/theme-img/game/memory-cards/gaming-14.png",
    "../assets/image/theme-img/game/memory-cards/gaming-15.png",
    "../assets/image/theme-img/game/memory-cards/gaming-15.png",
    "../assets/image/theme-img/game/memory-cards/gaming-16.png",
    "../assets/image/theme-img/game/memory-cards/gaming-16.png",
    "../assets/image/theme-img/game/memory-cards/gaming-17.png",
    "../assets/image/theme-img/game/memory-cards/gaming-17.png",
    "../assets/image/theme-img/game/memory-cards/gaming-18.png",
    "../assets/image/theme-img/game/memory-cards/gaming-18.png",
]
